### ISSUE TITLE
the subscribe button and contact form not responding to this site www.watedtz.org

### ISSUE THREAD

**Issue by honory2009** [Designmodocom/WP-Maintenance-Mode#105]
This site www.watedtz.org is under maintanance mode but the subscribe button and contact form they do not respond after being clicked. Any reason for their non response?

tks

hja

**Comment by georgejipa** [comment]
You can solve it by yourself by editing following this link: https://github.com/Designmodocom/WP-Maintenance-Mode/issues/85
Hope I'll have time ASAP to release the new version. :)

**Comment by honory2009** [comment]
Hi,
 
just checking to see if you have released an updated version.
 
thanks 
 
Honory
 
Date: Mon, 11 May 2015 16:08:18 -0700

**Comment by georgejipa** [comment]
Solved in 2.0.6. Thanks.
