### ISSUE TITLE
Contact E-mail says it's been sent but nothing being received 

### ISSUE THREAD

**Issue by neildockar** [Designmodocom/WP-Maintenance-Mode#110]
Hi There,

just put a simple holding page together at:

http://www.englishrose.eu

and all is displaying great.  However when you click on the "contact",  the form displays fine and you also get the successful "e-mail" received message, but the message isn't actually being received!

We are using amelia@englishrose.eu as the e-mail to receive

Really appreciate some help

Many thanks

**Comment by fcolpron** [comment]
Having the same problem.

WordPress 4.3.1 and WP-Maintenance-Mode 2.0.3.

SMTP settings known to be working since I can send and receive test emails with the WP-Mail-SMTP plugin (version 0.9.5).

Nothing received either in Inbox or Spam folder. No log to be found.

**Comment by tech55541** [comment]
My thoughts:
Working fine for me. I am using an SMTP Account to send mail. Could be a problem with the WordPress internal mail function. Try and reset your password and see if you get an email, if you do, it is plugin related, if you don't, it is WordPress related.
