### ISSUE TITLE
Redirection to custom URL not working

### ISSUE THREAD

**Issue by alordmg** [Designmodocom/WP-Maintenance-Mode#112]
I configured WP Maintenance Mode to redirect to a custom URL on my site and it doesn't work.

Here's my settings : 

![capture d ecran 2015-07-16 a 4 16 17 pm](https://cloud.githubusercontent.com/assets/11218493/8734156/1228975e-2bd6-11e5-881c-62083bf40c36.png)

I still see this page : 

![capture d ecran 2015-07-16 a 4 17 22 pm](https://cloud.githubusercontent.com/assets/11218493/8734170/28cd61c4-2bd6-11e5-8a7b-d8b6e5a8071c.png)

Instead, I should have this page : http://publafabrik.ca/attente/

![capture d ecran 2015-07-16 a 4 17 55 pm](https://cloud.githubusercontent.com/assets/11218493/8734179/39cf85ec-2bd6-11e5-803c-3bb06562f4ef.png)

**Comment by JomacInc** [comment]
I know this is old but found it after having same issue. Looks like the plugin is not designed to work the way I and the OP expected. I made a small change as below to get the desired result (perhaps in the future this will be an option).

In the file /includes/classes/wp-maintenance-mode.php
Change line 76 from:
`if (!is_user_logged_in() || !is_admin()) {`
To this:
`if ($GLOBALS['pagenow'] === 'wp-login.php' || is_admin()) {`

**Comment by cmlbrunn** [comment]
I have the same question as described by alordmg but I cannot find the code snippet JomacInc recommended to change. Are there any updates about how to make the redirection option work for the "WP Maintenance Mode" plugin?

**Comment by georgejipa** [comment]
The redirection feature is working but is not working the way you need.

https://wordpress.org/support/topic/redirect-option-does-not-work/#post-11351002
