### ISSUE TITLE
Changing the subscribe validation text: has a typo right now. 

### ISSUE THREAD

**Issue by theexplorationists** [Designmodocom/WP-Maintenance-Mode#113]
Hi, how can I change the subscribe buttons, validation text, right now is say "thank you for successfuly subscribing" or whatever, but successfully has a typo. 

Can there be a custom field text there?

**Comment by georgejipa** [comment]
Hello,

You can edit the language files (wp-maintenance-mode-en_US.po wp-maintenance-mode-en_US.mo) with poedit. The edit will also be available in the next version. 

Thanks!
