### ISSUE TITLE
Custom CSS for the front view?

### ISSUE THREAD

**Issue by mikeSo88** [Designmodocom/WP-Maintenance-Mode#117]
Hallo,

... how can I use my own custom CSS for the front view?

For Example: Sometimes I need a frame or a border arround the text or a background color behind a text.

Is this not possible with WP-Maintenance-Mode?!
I mean, it should! ;)

Danke und Gruss

**Comment by georgejipa** [comment]
Hello,

It is possible if have some programming skills (there is a wordpress filter `wpmm_styles`, if you need to add a new css style), otherwise no. But I have to admit that could be a great option for the new version. Thank you!

**Comment by mikeSo88** [comment]
Hallo,

... great - many thanks for quick reaction!

No unfortunately - I don't know how can I use wordpress filter wpmm_styles! ;(
Do mean this?: add_filter('wpmm_styles', 'myCSSclass', 1);

Can u give temporaly a workarround for this, until you give out - the next generation (with the great custom css option in the admin area) of your great plugin!

Danke und Gruss

**Comment by georgejipa** [comment]
There is a simple workaround but also require some skills. You can make a new file called "wp-maintenance-mode.php" in /wp-content/ and copy the content from "views/maintenance.php" (wp maintenance mode folder). This way... the plugin will load "wp-maintenance-mode.php" from /wp-content/.

And... of course, you can edit "wp-maintenance-mode.php" as you need.

**Comment by mikeSo88** [comment]
Hallo,

... great - many thanks for quick reaction and help!

Danke und Gruss
