### ISSUE TITLE
No Email when site comes back up

### ISSUE THREAD

**Issue by tech55541** [Designmodocom/WP-Maintenance-Mode#120]
Hello,
There is no email sent when the site comes out of maintenance mode. I tested it with Gmail, nothing ever gets sent. Checked all spam folders. Currently using this plugin for my email for WordPress.
https://wordpress.org/plugins/wp-mail-smtp/

**Comment by tech55541** [comment]
What is the progress of this? Is this plugin still being developed?

**Comment by georgejipa** [comment]
The plugin is not sending any email when the site comes out of maintenance mode...because doesn't have this feature. You can do that... by collecting emails and send them a newsletter with mailchimp (or any other newsletter provider).
