### ISSUE TITLE
Buttons not working

### ISSUE THREAD

**Issue by bgdesignz** [Designmodocom/WP-Maintenance-Mode#123]
I followed the instructions at this link:

https://wordpress.org/support/topic/no-countdown-no-email-capture-contact-us-not-working

The buttons seem to work on the computer however not on mobile devices. Anyone else come across this?

**Comment by hthumbo** [comment]
Hi bgdesignnz,

Recently I installed the plugin WP Maintenance Mode and I had the same issue.
After 2min of CSS debug I found the solution. Please check on the following link https://wordpress.org/support/topic/wp-maintenance-mode-subscribe-button-error-on-mobile-version?replies=1

Kind regards,
Hostilio Thumbo

**Comment by georgejipa** [comment]
Thanks @hthumbo! Your idea will be included in the next release.
