### ISSUE TITLE
Warning: strstr() [function.strstr]: Empty delimiter 

### ISSUE THREAD

**Issue by MrPlumbum** [Designmodocom/WP-Maintenance-Mode#125]
Warning: strstr() [function.strstr]: Empty delimiter in [...]/wp-content/plugins/wp-maintenance-mode/includes/classes/wp-maintenance-mode.php on line 614

when there is an empty line in the exclude input field

**Comment by georgejipa** [comment]
Solved in 2.0.6. Thanks.
