### ISSUE TITLE
how can i display an site notice (really important and a must for german website)

### ISSUE THREAD

**Issue by steveone1** [Designmodocom/WP-Maintenance-Mode#137]
Do you have a idea or a workaround how i can display my site notice?

Thanks

**Comment by georgejipa** [comment]
Hello,

Please give more details. 

Thanks.

**Comment by steveone1** [comment]
I need a link on the webpage like "Site notice"

Here from Wikipedia:

> The Latin word Impressum (printed, from the verb imprimĕre, i.e. to print), used in German, has no exact translation in modern English. It is a legally required statement of the ownership and authorship of a document, which must be included in books, newspapers, magazines and websites published in Germany and other German-speaking countries.

So i need a little link "Site notice/Impressum" to write the ownership and all the other things down.

**Comment by georgejipa** [comment]
Now I understand what you need, but we don't have this feature.

You can try to upload a html with that "Site notice/Impressum" in public_html and after that:
1. insert a link to that html file from (plugin) _Settings > Design > Content > Text_ textarea.
2. insert a link to that html file using a hook:

```php
// place it in functions.php of your active theme
add_action('wpmm_footer', 'wpmm_add_impressum_link');

function wpmm_add_impressum_link() {
    echo '<a href="http://domain.com/path_to_impressum_html" style="display: block; text-align: center;">Impressum</a>';
}
```
I think the first choice is more suitable for you.
