### ISSUE TITLE
Remove all data incl meta description

### ISSUE THREAD

**Issue by maxholgasson** [Designmodocom/WP-Maintenance-Mode#138]
Hi,

is it possible to output only the "maintance"-text without meta-data like description of the website?

**Comment by Mahjouba91** [comment]
Hi, what can of meta-data are you talking about please ? Can you provide some screenshots, or some new explanation to understand you problem well.

**Comment by maxholgasson** [comment]
Hello,

I mean that kind of data
http://www.w3schools.com/tags/tag_meta.asp

It would be nice if it is just a plain site with the title and text why it's down

I hope it's clearer what I meant

Have a nice day
Max

**Comment by Mahjouba91** [comment]
I don't really understand your request since the plugin only add important meta tag like title, viewport, description, author and robots, It doesn't interfer with your website. You can look the source code of your normal WordPress page, you will see 10 more times tags in the head tag.

**Comment by maxholgasson** [comment]
Ok,
Yes but i also would like to remove my tags from the website
.
Everything should be removed besides of the regular html structure and the text that says that the website is under  maintenance

Is it now clearer ?

**Comment by Mahjouba91** [comment]
Ok, so proceed like that :

1. Create a wp-maintenance-mode.php in your wp-content folder
2. Make the HTML markup you want, it's an empty file without any WP folks
3. To display the maintenance message, just echo this var : `echo stripslashes( $text );`
