### ISSUE TITLE
Change Server Code from 503 to 302

### ISSUE THREAD

**Issue by WCDigital** [Designmodocom/WP-Maintenance-Mode#141]
When I enable the maintenance mode, the server status changes to 503; Page temporarily unavailable.
This has an impact for visibility in search engines and they remove the page from the index

Please change server code response from 503 to 302 (or 200 is best)

**Comment by georgejipa** [comment]
Please read this: https://yoast.com/http-503-site-maintenance-seo/

Also, code 302 means Moved temporarily... which is not recommended for a website in maintenance mode.

**Comment by WCDigital** [comment]
I agree with this for a normal maintenance page, but I wanted to use it as a holding page, so I guess Im using the wrong plugin then...?

**Comment by georgejipa** [comment]
If you really need to return another response code, you can use `wpmm_status_code` filter.

```php
add_filter('wpmm_status_code', 'custom_wpmm_status_code', 10, 1);
function custom_wpmm_status_code($code){
	return 200;
}
```
Place this snippet in functions.php of your active theme and the response code will be 200. Right now I don't have an easier solution.

**Comment by jepperaskdk** [comment]
Would be great if this was configurable from the settings, rather than as code.
