### ISSUE TITLE
I enter my ipaddress and does not react at all

### ISSUE THREAD

**Issue by TrueType** [Designmodocom/WP-Maintenance-Mode#142]
dont' get it how the ip-address should be entered so it is regarded. I put in the excludes, no reaction.

**Comment by georgejipa** [comment]
Hello,

One IP address per line. Do you use any proxy/load balancer solution for your backwend web server(s)? If yes, you have to forward the real IP address of the user to the backend servers.

If you're using nginx, it can be done this way:

https://easyengine.io/tutorials/nginx/forwarding-visitors-real-ip/

Thanks.
