### ISSUE TITLE
User List from notification subscription

### ISSUE THREAD

**Issue by ryannsw** [Designmodocom/WP-Maintenance-Mode#143]
Is it possible to see a list of users who subscribed to be notified when the site is back online?

**Comment by georgejipa** [comment]
Hello @ryannsw,

1. There is no notification. Just subscribe. 
2. If you want to see the list, then it can be exported as CSV from plugin settings > Modules > Subscribe.

If you want to notify them... you should you a newsletter service + import the list.

Thanks.
