### ISSUE TITLE
contact form submit not working

### ISSUE THREAD

**Issue by sireeshav** [Designmodocom/WP-Maintenance-Mode#146]
XMLHttpRequest cannot load http://websitename.com/wp-admin/admin-ajax.php. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://kurubas.co.in' is therefore not allowed access.

**Comment by georgejipa** [comment]
Hello,

Use http://www.kurubas.co.in/ instead of http://kurubas.co.in/. Or at least change the url of the blog from settings and you won't have problems with cross-domain requests.

Thanks.
