### ISSUE TITLE
Cannot see Text Menu

### ISSUE THREAD

**Issue by saxjammin** [Designmodocom/WP-Maintenance-Mode#150]
I really like this plugin, I have it installed on another site however I am building a new site and it is a clean install everything has installed correctly and i am now ready to start working on it. I installed the wp maintenance mode plugin it installed ok however when i go to settings and select the design tab I cannot see any of my message only if I left click in the box to highlight but when I remove my finger from the left click I cannot see any message again. Also there is no menu above the text box, I cannot select bold, italic, align, etc   It will not switch from visual to text on the tab
Anyone have any idea what is the problem!!!!

**Comment by georgejipa** [comment]
Hello @saxjammin,

Please post a screenshot or a video (would be better).

Thanks.

**Comment by saxjammin** [comment]
Hi thanks for the reply, the only plugin i have installed is virtue pinnacle toolkit as recommended to go wit the virtue theme,

![wp maintenance issue](https://cloud.githubusercontent.com/assets/23383560/20213308/fb110f9a-a7ff-11e6-9ca7-51aebbeff713.jpg)

**Comment by georgejipa** [comment]
Hello,

With [Virtue / Pinnacle ToolKit](https://wordpress.org/plugins/virtue-toolkit/) plugin and [Virtue](https://wordpress.org/themes/virtue/) theme installed... everything works fine. Please check if there are any errors in Firebug console (Firefox) or DevTools console (Chrome).

Thanks.
