### ISSUE TITLE
Wp maintenance mode stuck

### ISSUE THREAD

**Issue by MeeRulz** [Designmodocom/WP-Maintenance-Mode#152]
Hello i installed your plugin wp maintenance mode on www.rillinternational.com now i have finished working on my site and trying to deactivate plugin, my site still shows Maintenance mode. plz tell me how do i fix this, i even tried deleting plugin but didnt work, i tried looking for .maintenance file in root directory there is no file. could you plz help me in this matter, my site is showing this page since 2 days now. any quick response would be highly appreciated. thanks/

Regards

**Comment by georgejipa** [comment]
Hello,

As I see, you have page cache plugin. So... I recommend to delete/refresh the page cache after you de-activate the maintenance-mode.

Thanks.

**Comment by MeeRulz** [comment]
Hello Georgejipa, i have done so many time refreshing the page after cache,
do you want me to delete all folders in /wp-content/endurance-page-cache?
![untitled](https://cloud.githubusercontent.com/assets/24291635/20790391/1cb3c5c2-b7f3-11e6-9f69-f04cfd266128.png)

**Comment by georgejipa** [comment]
Yes.

**Comment by MeeRulz** [comment]
Thanks georgejipa, it worked, been trying since ages. thanks a bunch. cheers.

**Comment by georgejipa** [comment]
You're welcome. I've also created a [pull request](https://github.com/bluehost/endurance-page-cache/pull/6) and I hope the author will accept it to fix the issue. :)
In a future release of WP Maintenance Mode I will try to delete/refresh the cache (generated by endurance-page-cache) when the maintenance mode is activated/de-activated.

Thanks.

**Comment by MeeRulz** [comment]
Hi again Georgejipa, sorry to bother you again,i am facing another problem, when i try to post link on facebook it still says "Maintenance mode" as a title as you can see in attached image. i tried going looking into>dashboard>settings>General. but everything seems fine there"site title says"Welcome to Rill International" . how do i fix this.?
![main](https://cloud.githubusercontent.com/assets/24291635/20794396/1163d7d4-b807-11e6-933e-41feee70db40.jpg)

**Comment by georgejipa** [comment]
Facebook... also is saving the details in cache. So... you have to use: 

https://developers.facebook.com/tools/debug/sharing/
