### ISSUE TITLE
Subdomain-Multisite-Problem

### ISSUE THREAD

**Issue by V-H** [Designmodocom/WP-Maintenance-Mode#156]
Hi!

Thanks a lot for that plugin! Works fine on single-site installation as well as on multi-site, … until I changed the multisite-type to “Subdomain”. In the backend I’m logged in as Superadmin and go to my primary website – the Maintenance-page appears instead of my site-pages with the admin-toolbar in top.

The plugin is not activated for the network – I’ve activated it in my primary website.

Any suggestions?

Thanks, so far...

**Comment by georgejipa** [comment]
Hello @V-H,

Right now I can't give you a solution. First of all I have to do some tests on my own and after that I will release a new version.

Thanks.

**Comment by V-H** [comment]
Problem solved! I switched between different sites of my multisite network and some login/logout sequences were probably not closed properly, because of plural login on the same machine under the same browser. So I deleted all WP-Cookies - and it works!
On the fly, a little wish: What's about a toogle in the admins-bar?

**Comment by georgejipa** [comment]
I'm glad you solved the problem. Anyway, I'm gonna do some tests just to be sure.

> On the fly, a little wish: What's about a toogle in the admins-bar?

Already on the to do list. Keep in touch! ;)

**Comment by V-H** [comment]
Hi George,

OK. Another idea: I found in your code, that the file
wp-maintenance-mode.php is checked in the wp-content folder. Great
stuff, don't let it die! Is there a chance for an option to use this
feature oder not? So, on multisite solutions users can decide, if they
want to use their own stuff as in the database stored or if they want to
use a general solution, as in wp-content/wp-maintenance-mode.php stored...

Regards,

Volker

Am 23.02.2017 um 19:23 schrieb George Jipa:
> I'm glad you solved the problem. Anyway, I'm gonna do some tests just to be sure.
>
>> On the fly, a little wish: What's about a toogle in the admins-bar?
> Already on the to do list. Keep in touch! ;)
>

**Comment by georgejipa** [comment]
We will take your idea into consideration, but I can't promise anything. :)
