### ISSUE TITLE
Maintenance mode is not displayed

### ISSUE THREAD

**Issue by claramontseny** [Designmodocom/WP-Maintenance-Mode#158]
Hello, 

When I set the status to "activated", the maintenance mode is not displayed. I have used this plugin smoothly so many times, but this issue is happening since 2.08 version. I have tried reinstalling the plugin, but I can't make it work properly. I updated to the last version, but this error persists. Can anyone help me, please? 

Thank you very much!
![captura de pantalla 2017-03-31 a las 17 59 40](https://cloud.githubusercontent.com/assets/26821293/24559158/fbbad668-163d-11e7-8205-ec57ecb934f1.png)
![captura de pantalla 2017-03-31 a las 18 00 59](https://cloud.githubusercontent.com/assets/26821293/24559167/051aa51c-163e-11e7-9d91-c703f3c0f528.png)

**Comment by georgejipa** [comment]
Hello @claramontseny,

Have you solved the problem?

Thanks.

**Comment by claramontseny** [comment]
Hello @georgejipa ,

Thank you for your concern. The maintenance mode is displayed properly. Sorry, I realized my blunder when I tested it with another browser. 

Kind regards,
