### ISSUE TITLE
Custom font not working

### ISSUE THREAD

**Issue by max23468** [Designmodocom/WP-Maintenance-Mode#161]
I’d like to change the font of the text in the maintenance page, using a custom font, but it’s not displayed in the browser even if the editor in the settings shows it.

**Comment by georgejipa** [comment]
Hello @max23468,

The answer for your issue is posted on wp.org. Next time please open just one ticket.

https://wordpress.org/support/topic/design-text-is-forced-in-an-h2/#post-8263762

Thanks.
