### ISSUE TITLE
Cant see maintenance mode at all!

### ISSUE THREAD

**Issue by rockingfun** [Designmodocom/WP-Maintenance-Mode#165]
I tried using other browsers and also incognito as well. nothing seem to work. i activated the mode alr. what am i doing wrong here?

**Comment by georgejipa** [comment]
@rockingfun do you use a cache plugin or cloudflare? if yes, clear the cache.

**Comment by rockingfun** [comment]
What is a a cache plugin or cloudfare?

**Comment by georgejipa** [comment]
- https://themeisle.com/blog/caching-in-wordpress/
- https://www.cloudflare.com/

**Comment by rockingfun** [comment]
I don't see either on my dashboard. Do I have to install WP cache for this
to work?

**Comment by georgejipa** [comment]
No... you don't have to install them. I've asked you about them because they usually cause this kind of issues.
Maybe you should post a screenshot with all your installed plugins. Also please specify the URL of your website (where WP Maintenance Mode is installed and Maintenace Mode is activated).
