### ISSUE TITLE
Can an Uploaded Background Have a Mobile Friendly Version?

### ISSUE THREAD

**Issue by grantburkhardt** [Designmodocom/WP-Maintenance-Mode#166]
Hi guys - I uploaded a custom image into the plugin (1920x1280px) and it looks great on desktop and tablet (!!), but it's not mobile-optimized. Is there a way for me to upload a separate mobile-optimized image for phone users?

**Comment by georgejipa** [comment]
Hello @grantburkhardt,

Actually, the background is responsive (background-size: cover;) but you can't display the same background size on all resolutions. 

If you want a custom background for smaller screens... you have to add custom css (loaded using plugin's hooks).

```php
// place it in functions.php of your active theme
add_action('wpmm_head', 'wpmm_custom_css');

function wpmm_custom_css(){
 // the css you need 
 echo '<style>
		@media only screen and (max-width: 767px) {
		  body {
			background-image: url(path/to/smaller/image.jpg);
		  }
		}
       </style>';
}
```
Thanks.

**Comment by grantburkhardt** [comment]
Thanks, George! That 767px max-width tag...is that a specific number for something or can I increase to fit bigger mobile devices (I think iPhone 7's are 1080px?)

**Comment by georgejipa** [comment]
@grantburkhardt: you're welcome. You can increase that width if you need.
