### ISSUE TITLE
Maintenance mode could not be deactivated

### ISSUE THREAD

**Issue by jevegat** [Designmodocom/WP-Maintenance-Mode#167]
I have activated Maintenance Mode in my site. I logout and close the wp-admin page and now I can't sign in wp-admin again to deactivate. It always redirect to Maintenance Mode page.

What can I do to deactivate?

**Comment by georgejipa** [comment]
Hello @jevegat,

1. Try to delete plugin's folder from /wp-content/plugins/
2. Please post the URL of your website.

Thanks.
