### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by elpedriyo** [Designmodocom/WP-Maintenance-Mode#168]
I have it enabled, with a picture and so, but it always displays the same message:

![image](https://user-images.githubusercontent.com/3207791/29809846-06c31ba2-8c9e-11e7-91e8-25f8d6889c31.png)

Any idea why can this be happening

**Comment by georgejipa** [comment]
Hello @elpedriyo,

It looks like your web server is not configured properly. Tell your hosting provider that you want to handle 503 errors using your php application, but the webserver is replacing the maintenance mode with a custom error page.

Thanks.

**Comment by joostdekeijzer** [comment]
For me, adding the following to .htaccess helped:

`ErrorDocument 503 /index.php`
