### ISSUE TITLE
Text field not displaying after updating to 2.1.1

### ISSUE THREAD

**Issue by zefflubrano** [Designmodocom/WP-Maintenance-Mode#173]
Hi,

Today I updated the plugin on my Wordpress page to the latest version 2.1.1. After the update, the text wasn't displaying in Maintenance mode. Luckily I was able to fix it. The bot deactivate/activate button had no value selected (so neither deactivate or activate was selected), and I think that caused the problem.

I've had it on two separate Wordpress sites, so I guess I have reason to believe that it's a small initialization mistake in the update. But then again I use similar set-ups on my sites.

Anyways, wanted to report this, 'cause the plugin is great.
Greatful for your contribution to the Wordpress community!

**To Simulate And Fix The Bug **
1. Have your site already on maintenance mode in the previous version.
2. Have title, heading and text filled in.
3. Update and see the text disappear.
4. Go to the bot tab and see neither deactivate/activate selected.
5. Select deactivate and your text is back in play. Or you forget about your whole text and try out the new bot feature ofcourse ;)!

But yeah, initializing the bot with deactivate or fixing the plugin of not failing whenever neither of the options is selected would be a potential fix to a potential bug!

Cheers,
Zeff

**Comment by zreedeecom** [comment]
We are aware of the problem and apologize for the inconvenience. We will be releasing a patch in the next 24h. Thanks for reporting.

**Comment by zreedeecom** [comment]
We just pushed an update to github repo. It will be soon available through WordPress repository.

**Comment by zefflubrano** [comment]
Awesome, there were no serious inconveniences at all pal! You're welcome and thanks!
