### ISSUE TITLE
Bot Susceptible to XSS

### ISSUE THREAD

**Issue by thehappydinoa** [Designmodocom/WP-Maintenance-Mode#176]
Susceptible to XSS:
```html
<w="/x="y>"/ondblclick=`<`[confir\u006d`test`]>Test
```

**Comment by zreedeecom** [comment]
Hi @thehappydinoa thanks for pointing out, we will look at it asap.

**Comment by thehappydinoa** [comment]
@zreedeecom Great, this is terrible.

**Comment by Medialo** [comment]
I confirm the robot has this bug, and it is possible to create a condition, that for example, for fields that the user can fill, that if characters like"< >" are entered, it returns an error?

**Comment by georgejipa** [comment]
A little bit late, but the issue is finally solved in release 2.2.4. I've decided to strip all HTML tags from user responses.

https://github.com/Designmodocom/WP-Maintenance-Mode/releases/tag/2.2.4
