### ISSUE TITLE
GDPR

### ISSUE THREAD

**Issue by greenhalos** [Designmodocom/WP-Maintenance-Mode#182]
What about GDPR for the subscription feature? The e-mail will be saved on the server and processed when downloaded as `csv`.

**Comment by zreedeecom** [comment]
Hi, we are on it. We will be rolling an update to give you (the webmasters) the option to show the corresponding notices, as well as the integration with latest wordpress privacy features.

**Comment by w4pnemsak** [comment]
any news on this? we're 2 days away from deadline.

**Comment by zreedeecom** [comment]
Hi guys, you can update your plugin to get the new gdpr feature. Note that we will be making changes and improvements during the next weeks.
