### ISSUE TITLE
create_function() deprecated in PHP 7.2

### ISSUE THREAD

**Issue by bunglegrind** [Designmodocom/WP-Maintenance-Mode#186]
hello,
I noticed that your plugin uses create_function() which is deprecated in PHP 7.2.

http://php.net/manual/en/migration72.deprecated.php

wp-maintenance-mode\includes\classes\wp-maintenance-mode.php line 865 and line 866
wp-maintenance-mode\includes\functions\helpers.php Line 11

Cheers

**Comment by zreedeecom** [comment]
I just merged @georgejipa 's pull request. We will be updating the WordPress Repo shortly but feel free to grab an updated copy from [github](https://github.com/Designmodocom/WP-Maintenance-Mode/releases/tag/2.2.1).

Thanks @georgejipa

**Comment by bunglegrind** [comment]
Thanks!
