### ISSUE TITLE
Recover email list

### ISSUE THREAD

**Issue by coco4444** [Designmodocom/WP-Maintenance-Mode#193]
Hello,

I hope that you can help me, it is very important.

For months I had a coming soon page using your WP maintenance mode. I asked people to put their email to registrer to the database.
But few days ago I decided to connect my website to Shopify instead of WordPress.
And now I can not connect anymore to my WordPress admin and so I can not go back to your plugin and I can not import my database.

What can I do? Can you help me having my list back? I have so many emails on it ...
Thank you so much.
Best,

**Comment by georgejipa** [comment]
@coco4444 if you have a backup of your mySQL database, you can recover the list by exporting `wp_wpmm_subscribers` (replace wp with your prefix) table. :)
