### ISSUE TITLE
maintenance mode stopped working when I moved my wp site location. 

### ISSUE THREAD

**Issue by georgey58** [Designmodocom/WP-Maintenance-Mode#194]
I moved my site to another folder (following all the instructions on how to do this) and everthing is working ok except that WP_Maintenance-Mode doesn't affect the site anymore. There must be something more I have to update. I looked at wp_options table (It is a Multisite installation) but can't see any reference to the site url specifically for WP_MM. Where should I be looking?

**Comment by georgejipa** [comment]
WP MM doesn't use the URL of the website to display the maintenance page.

You should try to:
1. log out -> log in 
2. reinstall the plugin (uninstall -> install)
