### ISSUE TITLE
"How you can export the email addresses" notice on "Manage Bot" settings tab

### ISSUE THREAD

**Issue by georgejipa** [Designmodocom/WP-Maintenance-Mode#195]
I think we should add a notice about how you can download/export the email addresses collected using the bot.

https://wordpress.org/support/topic/bot-where-are-the-email-addresses-stored/
https://wordpress.org/support/topic/simple-et-efficace-80/

**Comment by zreedeecom** [comment]
Yeah, looks like it's not as obvious I thought. Will add a little note under the bot tab.

**Comment by georgejipa** [comment]
Done in release 2.2.4.

https://github.com/Designmodocom/WP-Maintenance-Mode/releases/tag/2.2.4
