### ISSUE TITLE
Security vulnerabilities

### ISSUE THREAD

**Issue by KdiagHaci** [Designmodocom/WP-Maintenance-Mode#197]
Hey , Designmodcom Team

I found the relevant security vulnerability in your plugin, can I have a pipeline report?

(ex: e-Mail reports to your team) Or are my reporting directly on GitHub?

Thanks~

**Comment by planetahuevo** [comment]
Has this been reported and fixed?

**Comment by Designmodocom** [comment]
We have not received any report related to this issue. We close this thread now, hope the author will send us an email.
