### ISSUE TITLE
After deactivating WP-Maintenance Mode site displays 502 Bad gateway

### ISSUE THREAD

**Issue by Sarisbonita** [Designmodocom/WP-Maintenance-Mode#199]
Hello, I change the content of my site and used theWP-Maintenance Mode plug in while I was working in the new content. Everything was looking good, and well functioning. 

While I was logged out the coming soon page appears, and when I was logged in as the admin I was able to navigate in the website and continue making changes  with no problem.

Once I finish the changes, I deactivated the WP-Maintenance-Mode plug in in the option inside the plug in config, and when I refresh (as a regular user/ not admin) the site showed 502 error, I tried to deactivate completely the plug in from the plug ins section on WP, and still the same error.

As soon as I activate the WP-Maintenance-Mode again, the coming soon page came on again.

I don't know if a file was deleted or what happened. The site is visible for all users (including non registered) just with the plug in enabled and activated, but as soon as its deactivated, just come in the bad gateway error.

![captura de pantalla 2018-09-22 a la s 14 03 17](https://user-images.githubusercontent.com/43503109/45920900-c07f8f80-be70-11e8-93c1-114809c44024.png)
This is regular user or not logged user while WP-Maintenance Mode  is activated

![captura de pantalla 2018-09-22 a la s 14 00 48](https://user-images.githubusercontent.com/43503109/45920910-ddb45e00-be70-11e8-8059-f97c49561dbd.png)
This is how it looks when Im logged in as admin, with the WP-Maintenance Mode activated or deactivated, but logged as admin

![captura de pantalla 2018-09-22 a la s 14 00 14](https://user-images.githubusercontent.com/43503109/45920917-f91f6900-be70-11e8-92b7-1d7403d2bd1e.png)
This is how the site looks like when WP-Maintenance Mode  is deactivated and Im not logged in. or in the view for non registered users.

I tried in different browsers, devices and removing cookies, and its exactly the same result.

I really do appreciate if someone can help me to fix it.

Thank you.

**Comment by Sarisbonita** [comment]
Hello, yes, but no problem. 
I was verifying other options, and it seems the problem is the compatibility with another plug in -Carrousel Horizontal posts- this plugin can't be activated at the same time as WP-Maintenance Mode is installed in the WP , as soon as I deactivated the carrousel, the website came on again. 
I'm not sure if this is the unique reason or there is something else that could be causing the problem, because I did not found nothing about it in the documentation of none of this two plugins.
This can be a good feedback to include in the documentation :D 
Thank you.

**Comment by georgejipa** [comment]
@Sarisbonita Thank you for your feedback. We will make some tests with both plugins and see what happens.

Please confirm if this is the plugin you're talking about:
https://wordpress.org/plugins/carousel-horizontal-posts-content-slider/

**Comment by Sarisbonita** [comment]
No problem, I hope I can help a little bit with the issue I had, and Yes it is. 
Thank you.

**Comment by georgejipa** [comment]
@Sarisbonita I've installed and activated the latest versions of both plugins, and everything works fine. 
Even if I set WPMM status to "Deactivated" or deactivate the plugin, the other plugin works as intended. I'm pretty sure there is no incompatibility between them.

My guess? That plugin (Horizontal Carousel posts) is incompatible with your theme or another plugin, and the issue occurs when the users are not logged in.

**Comment by Sarisbonita** [comment]
Hello again, also I thought it was my theme but I tried with the default in WP (twenty seventeen and twenty sixteen) and I had the same issue.

The wp version I have is the latest in Spanish for Mexico. (This one https://es-mx.wordpress.org/txt-install/) 

I don’t know  if it could be related; and the theme I’m actually using is jnews pro.



Enviado desde mi iPhone

**Comment by georgejipa** [comment]
If it's not the theme, then it is a conflict with another plugin or maybe a problem in the plugin itself (Carousel Horizontal Posts). Unfortunately, I can't replicate the issue on my test environment.
