### ISSUE TITLE
Contact Us button gives no feedback

### ISSUE THREAD

**Issue by tybement** [Designmodocom/WP-Maintenance-Mode#206]
First off, I'm new and I apologize if this has been solved and I'm just too dumb to figure it out. 

When I hit the button nothing happens and the form stays up, no confirmation that it was sent. I have seen that this has apparently been fixed in newer versions, however my panel is telling me its at the latest version.

Any help is appreciated, thank you =)

**Comment by georgejipa** [comment]
@tybement please post the URL of the website where the plugin is activated.

**Comment by tybement** [comment]
You know....I don't know now. I re added the contact button for troubleshooting purposes and it works fine on my phone and pc now. Sorry to bother.

**Comment by tybement** [comment]
thank you for taking the time to respond. its much appreciated. Oddly it's
working as intended now.

**Comment by AminPersis** [comment]
Hello guys,

Contact button works on my website and says it's been sent, but nothing comes to the defined inbox. I've checked the mail server for inbound emails and it's working fine, but no messages from contact us button will be delivered. 

Regards

**Comment by georgejipa** [comment]
@AminPersis Have you tried to install an SMTP plugin?

https://www.wpbeginner.com/plugins/how-to-send-email-in-wordpress-using-the-gmail-smtp-server/
