### ISSUE TITLE
Love the bot but...

### ISSUE THREAD

**Issue by jeancharlesamey** [Designmodocom/WP-Maintenance-Mode#211]
Hello,
Since 2.2.3, the bot maintenance mode seems no more working. I notice is on my website, sadly had to turn it off.

Do you have also the problem ? 
Any way to commonly solve this ? 

Best regards

**Comment by jeancharlesamey** [comment]
Wrong alert,
I refresh, refresh, update, update, refresh, refresh, and it works again ! 

No comment !

**Comment by georgejipa** [comment]
Ok, I will close the issue. :)
