### ISSUE TITLE
Redirect can disable login in some circumstances

### ISSUE THREAD

**Issue by autotel** [Designmodocom/WP-Maintenance-Mode#214]
I am working on a new version of an existing wordpress site. As strategy to stage, I hosted the new version of the site in directory like: www.mydomain.com/staging. Since I want whoever got into the staging website to go to the main, older version, I set the redirect to the older site (mydomain.com). Now it became impossible to login until I disabled redirection. It seems that the login post data gets lost because of the redirection to a different domain.
I am using a bunch of other plug-ins, hence, if other users in similar circumstances have different outcome, it might as well be a conflict.
Wordpress version: 5.1.1

**Comment by georgejipa** [comment]
@autotel The redirection is working only if the user is logged in. So, if the user is redirected to the production URL, it means that it is logged in.

**Comment by autotel** [comment]
thanks! 
The option name led me to thing that it referred to non logged-in users
