### ISSUE TITLE
Problem: With adding front end and back end users

### ISSUE THREAD

**Issue by kirabe** [Designmodocom/WP-Maintenance-Mode#216]
My site is currently under Maintenance mode, but I would still like to add front-end and back-end users, so I added them under settings. However, when they try to access the site they still see the maintenance mode page. Is that a bug to do with my theme or how am I able to change that? Thanks.

**Comment by georgejipa** [comment]
@kirabe the feature works fine on our test environment (latest WordPress version).

1. Do you have a cache plugin or maybe a native cache solution (nginx, varnish)?
2. Have you checked if those users are logged in and have the right user roles?

**Comment by kirabe** [comment]
Thanks.

Tried it with different users they all had the same issue. Is it that that they always have to go in through the back end in order to get to the front end? Because they all can access the back end just the front end shows the maintenance page.

**Comment by georgejipa** [comment]
Yes, they always have to be logged in. And the only way to log in is to go the backend first.

**Comment by kirabe** [comment]
When I add them as a subscriber, there is no way for them to see the front end even though I added the role under settings. Anything else I could do?

**Comment by kirabe** [comment]
Would it help if I add a link to the dashboard on the maintenance site so they can easily access the back end?

**Comment by georgejipa** [comment]
@kirabe From what you're saying, I don't really understand what is not working anymore. 

The users don't know how to get to the login page? Go to plugin settings > "General" > set "Dashboard link" to "Yes". After that, they should see a link on the frontend.
