### ISSUE TITLE
Video Background

### ISSUE THREAD

**Issue by GWS14** [Designmodocom/WP-Maintenance-Mode#218]
Hi there,

When I first used the plugin, I found that the plugin was unable to hide my homepage. I noted that there was a short warning message over the video on the homepage that mentioned something about 'media' (sorry but I don't recall the full message). The video in question is a video background within a DIVI Module.  

When I navigated away from homepage (using the page menu), the subsequent pages would be be hidden, but whenever I went back to the home page URL, (where the video was located), the whole webpage was revealed again. 

Consequently, to hide the homepage, I had to temporarily remove the video from module background. Not the best solution but it worked. Is there a reason why the plugin didn't work on that page with the video background?

regards
GWS14

**Comment by georgejipa** [comment]
@GWS14 I'm not a Divi user, but I've managed to test what you're saying.

Here are the steps I've followed:

- create a new page

![edit page](https://user-images.githubusercontent.com/4528530/59682118-36394180-91de-11e9-8afa-ad7f83220b70.png)

- set a video background (downloaded from https://sample-videos.com/) on the first row

![edit row backgroud](https://user-images.githubusercontent.com/4528530/59682136-42250380-91de-11e9-8150-c72594f9917e.png)

![page](https://user-images.githubusercontent.com/4528530/59682187-59fc8780-91de-11e9-8cca-6fdff161ba58.png)

- set the new page as a static page for the homepage

The maintenance mode page is working on the homepage, whether I keep the video background or not. So, I think the issue has nothing to do with the video background. 

Do you have a cache plugin? Try to disable it.

**Comment by GWS14** [comment]
Ok. Thanks George.
