### ISSUE TITLE
Where is the email?

### ISSUE THREAD

**Issue by MORENOC** [Designmodocom/WP-Maintenance-Mode#220]
Hi.

I try to use the contact form when is in maintenance mode, but the mail never is received.

is possible to change the form? where could be changed?

could any help me?

thanks

**Comment by georgejipa** [comment]
Hello,

For good email deliverability, you should install an SMTP plugin:

https://wordpress.org/plugins/wp-mail-smtp/

And, yes, it is possible to change the form, but you need PHP & WordPress skills to make the changes.

- here you can find the hooks (`wpmm_contact_form_*`) that can help you to add new fields to the contact form: https://github.com/Designmodocom/WP-Maintenance-Mode/blob/master/views/maintenance.php#L128
- here you can find the hook (`wpmm_contact_validation`) that can help you to validate the new fields:
https://github.com/Designmodocom/WP-Maintenance-Mode/blob/master/includes/classes/wp-maintenance-mode.php#L889
- here you can find the hooks (`wpmm_contact_template_*`) that can help you to display the new fields in the emails:
https://github.com/Designmodocom/WP-Maintenance-Mode/blob/master/views/contact.php
