### ISSUE TITLE
Not showing up

### ISSUE THREAD

**Issue by MojoCrazy** [Designmodocom/WP-Maintenance-Mode#226]
I tried activating but for some reason, whatever theme I have just shows up instead of the maintenance page. I'm pretty new to all this and have no clue whatsoever what to do or how to move forward. Any help would be appreciated

**Comment by georgejipa** [comment]
@MojoCrazy have you tried in a different browser?

**Comment by MojoCrazy** [comment]
It seems to be working fine in IE and Firefox. I'm using chrome

**Comment by MojoCrazy** [comment]
I have changed it a few times and it works just fine in IE and Firefox with all the changes but I can't get it to work with chrome.

**Comment by georgejipa** [comment]
@MojoCrazy It won't work if you are logged in as an administrator. The purpose of the plugin is to display the maintenance mode page to guests and regular users. 
Try to logout, and it will work on Chrome too. :)

**Comment by MojoCrazy** [comment]
@georgejipa Thanks for the help, that sorted it all out. Much appreciated
