### ISSUE TITLE
meta_robots setting does nothing

### ISSUE THREAD

**Issue by diablodale** [Designmodocom/WP-Maintenance-Mode#227]
The "meta robots" settings in the admin UI seems to do nothing.

https://github.com/Designmodocom/WP-Maintenance-Mode/blob/113d857a071a53ef770d5a2a215786eacd7b39b6/views/settings.php#L77

I can see in the code the setting is migrated, and has a UI to save it. However, I can not see in the code anywhere that this setting is used and does anything.

Perhaps this setting is no longer needed.

**Comment by georgejipa** [comment]
https://github.com/Designmodocom/WP-Maintenance-Mode/blob/832162c9f3253f140b11223de19fd1c46abe9cc4/includes/classes/wp-maintenance-mode.php#L551

https://github.com/Designmodocom/WP-Maintenance-Mode/blob/832162c9f3253f140b11223de19fd1c46abe9cc4/views/maintenance.php#L10

**Comment by diablodale** [comment]
Yes, I am wrong. 🥴 My apologies.
I wasn't able to find that code with github search. I can now see and understand what that setting is doing.
Thank you for the correct and clarification! :-)
