### ISSUE TITLE
Allow non-admin to handle Maintenance options.

### ISSUE THREAD

**Issue by dademaru** [Designmodocom/WP-Maintenance-Mode#228]
I think it would be useful to have a hook to change capabilities in [`WP_Maintenance_Mode_Admin->add_plugin_menu`](https://github.com/Designmodocom/WP-Maintenance-Mode/blob/master/includes/classes/wp-maintenance-mode-admin.php#L223).

e.g.
```
$capability = apply_filters( 'wpmm_settings_capability', 'manage_options' );
```

For example in an eCommerce store, to allow a Shop Manager user to easily enable / disable the maintenance mode or change the text. 
Thanks.

**Comment by georgejipa** [comment]
@dademaru great idea! I will add the filter in the next release.

**Comment by georgejipa** [comment]
@dademaru done! Until we release a new version on WordPress.org, you can download the files from GitHub.

Now we have three filters for capabilities:
1. `wpmm_settings_capability` (default *manage_options*) - to change capability for settings page (show settings page, save options, reset options)
2. `wpmm_subscribers_capability` (default *manage_options*) - to change capability for subscribers module (export list, empty list)
3. `wpmm_all_actions_capability` (default *manage_options*) - to override capability for all actions

For example, if you use the last filter, you can set the same capability for all actions:

```php
add_filter('wpmm_all_actions_capability', function($capability) { 
    return 'custom_capability';
}, 10, 1);
```

**Comment by dademaru** [comment]
Hello @georgejipa 
thanks, great hooks!
