### ISSUE TITLE
Emails to Hotmail or Gmail are not received

### ISSUE THREAD

**Issue by DavidMG83** [Designmodocom/WP-Maintenance-Mode#231]
Hi!
When i try to set a hotmail or Gmail adress for the contact form, the email are not received.

Could you help me please?

**Comment by georgejipa** [comment]
For good email deliverability, you should install an SMTP plugin.

https://wordpress.org/plugins/wp-mail-smtp/
https://www.wpbeginner.com/plugins/how-to-send-email-in-wordpress-using-the-gmail-smtp-server/
