### ISSUE TITLE
SPAM comments while site is in "Maintenance Mode"

### ISSUE THREAD

**Issue by tmksr** [Designmodocom/WP-Maintenance-Mode#232]
Someone / Bot (noreply@exorank.com) wrote an article comment while my site is in "Maintenance Mode" - how is this possible?

**Comment by georgejipa** [comment]
The only way I think it's possible to do that is to send a POST request straight to http://domain.com/wp-comments-post.php

A good idea would be to automatically close the comments when the website is in maintenance. Maybe I'll add this idea in the next version.
