### ISSUE TITLE
Bot conversation doesn't get updated

### ISSUE THREAD

**Issue by Rayrsn** [Designmodocom/WP-Maintenance-Mode#235]
i tried to make a new conversation for my bot and it seems like it doesn't work properly, it gets saved in the settings for example when i go back to change the conversation the new conversation is still there but when i want to actually test the bot, it shows me tho old conversation. is there anyway to fix this?

**Comment by georgejipa** [comment]
Please check if `/wp-content/uploads/data.js` is also updated. The bot is using this file to load the settings.

**Comment by georgejipa** [comment]
If it's not updated, it may be a file permission issue. So you should change `/wp-content/uploads/` permissions to 755, and `/wp-content/uploads/data.js` to 644.

**Comment by Rayrsn** [comment]
the data.js file gets updated, but i still corrected the permissions and nothing changed

**Comment by georgejipa** [comment]
If the file is updated, maybe your browser cached the file? Have you tried a hard refresh?

Also, do you use a CDN for the static assets? If yes, you have to delete the cache.

**Comment by Rayrsn** [comment]
i tried disabling the ssl and it worked perfectly, I don't know why the ssl was interfering with it but it's fine now. thanks for responding
