### ISSUE TITLE
Not allowing IP through

### ISSUE THREAD

**Issue by Chrisifly** [Designmodocom/WP-Maintenance-Mode#236]
Hello

I have a site in maintenance mode and I have been only allowing certain IP addresses through to view the page. Recently it stopped working. The IP addresses that I list to let through are getting blocked and unable to see the website.

Your assistance in this regard will be highly appreciated.

**Comment by georgejipa** [comment]
Hello @Chrisifly,

It looks like the plugin can't detect the real IP address of your visitors anymore. Have you (or your hosting provider) changed the web server's configuration lately?

---
George

**Comment by Chrisifly** [comment]
Hi George,
We haven't changed anything lately. I deactivated the plugin and have reactivated now and it seems to be working again.

Chris
