### ISSUE TITLE
Plugin conflict with BeaverBuilder

### ISSUE THREAD

**Issue by adminslowlyslow** [Designmodocom/WP-Maintenance-Mode#237]
Hi, the WP Maintenance Mode plugin is causing a conflict with BeaverBuilder where BeaverBuilder will not start so long as the plugin is activated. The BeaverBuilder page will simply not load (no error messages).

**Comment by georgejipa** [comment]
Thank you for telling us. Are you talking about the lite version or the premium one?

**Comment by georgejipa** [comment]
Just tested the [lite version](https://wordpress.org/plugins/beaver-builder-lite-version/) and it works fine.

https://www.dropbox.com/s/yl8kb60hgkq9isi/Screenshot_2020-03-16%20test%20%E2%80%93%20wpmm.png?dl=0

**Comment by georgejipa** [comment]
It also works fine with the premium version (I've used [v2.3.1.3](https://community.wpbeaverbuilder.com/t/beaver-builder-version-2-3-1-3/11022))

Beaver Builder interface: https://www.dropbox.com/s/ixj5as05jxgbyp0/Screenshot_2020-03-16%20Beaver%20Builder%20Pro%20%E2%80%93%20wpmm.png?dl=0

Plugins interface: https://www.dropbox.com/s/8lurp0evrrlxm1s/Screenshot_2020-03-16%20Plugins%20%E2%80%B9%20wpmm%20%E2%80%94%20WordPress.png?dl=0
