### ISSUE TITLE
Combination with W3 Total Cache

### ISSUE THREAD

**Issue by dhunink** [Designmodocom/WP-Maintenance-Mode#81]
I do use W3 Total Chache and this wonderfull plugin. I noticed that when I disable the maintenance plugin, and even completely remove the plugin, the website still display's the maintenance page on some occasions (even after multiple purges of all W3 cache's). For example http://gtmetrix.com/reports/topografieindeklas.nl/PRGLLtM7 :
![schermafbeelding 2014-12-03 om 13 16 17](https://cloud.githubusercontent.com/assets/2500356/5280571/47ac48d8-7af3-11e4-9c2b-dd7ce8d93587.png)
But this was also happening on other computers, even ones that had never accessed the website.

So I ended up disabling W3 Total Cache, fetching the website again on gtmetrix.com, re-enable W3 Total Cache and re-fetching on gtmetrix. Unfortunately, the result then was again the same as in the screenshot above.

So for some reason W3 Total Cache and WP-Maintenace-Moda don't like each other. I Couldn't find out why. But what does bother me a LOT is the fact that even after removing WP-Maintenance, the website is still fetched with the maintenance screen. 

I Really need to know which files had been altered by WP-Maintenace and therefore were to look for hardcore removal of all references to WP-Maintance stuff. 

Hopefully someone can help me out!

**Comment by dhunink** [comment]
Hi George,
it's been over 2 months now since I removed the plugin. In the mean time the caching folder has been cleared multiple times...but i'm still getting report from users who receive the maintenance mode screen. Only way for them to get past is by trying to signup for email; that action will redirect to the website it self.

Any thoughts?

**Comment by georgejipa** [comment]
Sounds unbelievable... because the plugin is not altering any file... just adds some actions into init wp hook ONLY when is enabled. Are you sure W3 Total Cache is working fine ? Also please give me an url where the maintenance mode appears.

**Comment by dhunink** [comment]
I agree, sounds unbelievable. And i'm not saying i'm sure it's the plugin. But it does has to do something about it, since the plugin's screen is there.
W3 Total Cache seems to look perfect. Did emptied the caches several times and cleared out the Amazone CloudFront cache. 
The url on which users got the screen is https://topografieindeklas.nl

**Comment by clockworkmcd** [comment]
i'm not with the developers, was just looking through the issues, but for what it's worth your website looks fine from my end.

**Comment by dhunink** [comment]
Hi There! Just the other day I've logged in on a PC of which i'm certain hasn't accessed the website previously and indeed it showed the Maintenance screen. In addition, webceo.com did also received the website as the maintenance plugin was active, with 404 errors on it's JS and CSS files.

**Comment by danlinn** [comment]
@dhunink I found that Memcached was aggressively caching the maintenance page. A manual flush or a switch to file system caching fixed it for me.
