### ISSUE TITLE
Contact us button does not work

### ISSUE THREAD

**Issue by clockworkmcd** [Designmodocom/WP-Maintenance-Mode#85]
when you click the 'contact us' button on the website front end maintenance screen nothing happens. have tried all 3 effects.

**Comment by clockworkmcd** [comment]
and neither does the subscribe

**Comment by georgejipa** [comment]
Please try this fix: https://wordpress.org/support/topic/no-countdown-no-email-capture-contact-us-not-working
That fix is already included in the new version but I don't have time to release it right now. :)

**Comment by clockworkmcd** [comment]
changing that line did indeed fix it. thanks for your help!
