### ISSUE TITLE
Fix code for custom page support

### ISSUE THREAD

**Issue by antwal** [Designmodocom/WP-Maintenance-Mode#86]
Hi, 

I use your plugin, but every upgrade I need fix the source code; you can add support for custom page on theme path?

My Fix:
-                if (file_exists(WP_CONTENT_DIR . '/wp-maintenance-mode.php')) {
-                    include_once(WP_CONTENT_DIR . '/wp-maintenance-mode.php');
-                if (file_exists(get_template_directory()."/wp-maintenance-mode.php")) {
-                    include_once(get_template_directory() . '/wp-maintenance-mode.php');

Thanks.

**Comment by dackmin** [comment]
:+1:

**Comment by Mahjouba91** [comment]
Hi,

I have made a new PR for this issue, there are two differences between the first PR :
- First, check the child theme folder, then the parent theme folder to ensure both possibilities
- Then, The order priority is to check the child theme, parent theme, and then the WP content dir in my opinion.

Hope this will be merged soon, really need this feature for my web agency

**Comment by georgejipa** [comment]
Hello,

This will be merged in the next release. 

Thanks!

**Comment by Mahjouba91** [comment]
Thank you George :)
