### ISSUE TITLE
DB Notice on subscribe module

### ISSUE THREAD

**Issue by guillaumemolter** [Designmodocom/WP-Maintenance-Mode#91]
Hi,

I just installed your plugin for the first time. Great job! However in the module tab, subscribe section I get a WP Notice :

>Notice: wpdb::prepare was called incorrectly. The query argument of wpdb::prepare() must have a placeholder. Please see Debugging in WordPress for more information. (This message was added in version 3.9.) in /path-to-wp/wp-includes/functions.php on line 3547

It's nothing preventing me to use the plugin but you know...who likes errors and notices ;-) ??

I have an up to date WP install, in network mode with Debug activated.

Hope this helps

**Comment by guillaumemolter** [comment]
Not 100% certain as I haven't got a chance to try it yet but I believe the problem comes from here: 
(https://github.com/Designmodocom/WP-Maintenance-Mode/blob/7f1d97c1584c0370560ee0dec53a2001e06169e6/includes/functions/helpers.php#L28)

I think you should be using placeholders instead of putting vars directly inside the `prepare`

**Comment by georgejipa** [comment]
Hello,

Thanks for your pull request. I usually use placeholders just for WHERE, not for SELECT fields or table name. Anyway, the problem was already solved in the new version. Unfortunatelly didn't have time to do a public release. :)
