### ISSUE TITLE
user role checking

### ISSUE THREAD

**Issue by dpiquet** [Designmodocom/WP-Maintenance-Mode#93]
Hi,

I have a setup with custom roles. If i choose the custom role with the fewest capabilities as the allowed role, other roles (with at least all the capabilities given to the lowest role) cannot access the website

The plugin checks if a user is allowed to connect to website by calling the current_user_can function with a role as the parameter. According to the codex, current_user_can should be given capabilities as parameter, not roles ( http://codex.wordpress.org/Function_Reference/current_user_can ).

There are a few ways to deal with it, for example add a custom capability to allowed users or choose directly a core capability the user must have. Another solution would be to allow selecting multiple roles (but you would keep giving the current_user_can function a role as the parameter and this would not be great).

**Comment by georgejipa** [comment]
Hello,

1. Actually... you can use the role name too. :)

```php
/**
 * Whether current user has capability or role.
 *
 * @since 2.0.0
 *
 * @param string $capability Capability or role name.
 * @return bool
 */
function current_user_can( $capability ) {
	$current_user = wp_get_current_user();

	if ( empty( $current_user ) )
		return false;

	$args = array_slice( func_get_args(), 1 );
	$args = array_merge( array( $capability ), $args );

	return call_user_func_array( array( $current_user, 'has_cap' ), $args );
}
```

2. In v2.0.4 you will be able to select multiple roles and current_user_can function is not used anymore. Will be released after some tests.
![screenshot](http://pp.screenshotlink.ru/v2150/1c6/fNi3p177sUc.png)

**Comment by dpiquet** [comment]
Hi, 

I saw that you addressed this in the dev branch, forgot to update this ticket. Thanks for the screenshots by the way :) We can safely close it now.

Can't wait to see the latest version of your plugin released !
