### ISSUE TITLE
 [function.file-get-contents]: failed to open stream

### ISSUE THREAD

**Issue by iapassas** [Designmodocom/WP-Maintenance-Mode#95]
I got a function in a php file that echo a json object.
When the maintenance mode is active and I am calling my function the following "Warning" message appears:
Warning: file_get_contents(<i>the php file</i>) [function.file-get-contents]: failed to open stream: HTTP request failed! HTTP/1.1 503 Service Unavailable in  <i>the line of the php file</i>

When the maintenance mode is deactivated everything in the application works smoothly.

**Comment by georgejipa** [comment]
You should try to add the request_uri of that json to exclude list from plugin's "General" settings tab.

E.g.: if the url of that json is http://domain.com/url-to-that-json/, you should add into exclude list: url-to-that-json
